### ISSUE TITLE
Undefined method Prophecy\Prophecy\MethodProphecy::shouldReturn()

### ISSUE THREAD

**Issue by roukmoute** [phpspec/prophecy#279]
Hi,

I've a problem for create a stub.
I try to create this example:
```php
<?php

namespace spec\Site\Bundle\ApiBundle\View;

use PhpSpec\ObjectBehavior;

class JsonViewHandlerSpec extends ObjectBehavior
{
    function it_return_empty_data(\FOS\RestBundle\View\View $view)
    {
        $view->getStatusCode()->shouldReturn(200);
        $view->getHeaders()->shouldReturn([]);
        $this->createResponse($view)->getContent()->shouldReturn('{}');
    }
}
```

But I don't know why, I've got this message:
```
✘ Fatal error happened while executing the following 
    it return empty data 
    Uncaught Error: Call to undefined method Prophecy\Prophecy\MethodProphecy::shouldReturn() in /www-data/Site/spec/Bundle/ApiBundle/View/JsonViewHandlerSpec.php:11
Stack trace:
#0 [internal function]: spec\Site\Bundle\ApiBundle\View\JsonViewHandlerSpec->it_return_empty_data(Object(PhpSpec\Wrapper\Collaborator))
#1 /www-data/Site/vendor/phpspec/phpspec/src/PhpSpec/Runner/ExampleRunner.php(143): ReflectionMethod->invokeArgs(Object(spec\Site\Bundle\ApiBundle\View\JsonViewHandlerSpec), Array)
#2 /www-data/Site/vendor/phpspec/phpspec/src/PhpSpec/Runner/ExampleRunner.php(79): PhpSpec\Runner\ExampleRunner->executeExample(Object(spec\Site\Bundle\ApiBundle\View\JsonViewHandlerSpec), Object(PhpSpec\Loader\Node\ExampleNode))
#3 /www-data/Site/vendor/phpspec/phpspec/src/PhpSpec/Runner/SpecificationRunner.php(55): PhpSpec\Runner\ExampleRunner->run(Object(PhpSpec\Loader\Node\ExampleNode))
#4 /www-data/Site/vendor/phpspec/phpspec/src/PhpSpec/Runner/SuiteRunner.php(56): PhpSpec\ in /www-data/Site/spec/Bundle/ApiBundle/View/JsonViewHandlerSpec.php on line 11 
```

Have you an idea to resolve this?
Thanks

**Comment by nick-jones** [comment]
Promises (`will*()`) should be used to set the behaviour of stub methods, not predictions (`should*()`).. try changing

```
$view->getStatusCode()->shouldReturn(200);
$view->getHeaders()->shouldReturn([]);
```

to 

```
$view->getStatusCode()->willReturn(200);
$view->getHeaders()->willReturn([]);
```

**Comment by roukmoute** [comment]
Thanks !
